#!/usr/bin/env bash

set -ex

CONFIG="install.conf.yaml"
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${DOTBOT_DIR}"

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"

# neovim
cd /tmp
wget https://github.com/neovim/neovim/releases/download/v0.11.0/nvim-linux-x86_64.tar.gz
tar -xvf nvim-linux-x86_64.tar.gz > /dev/null
sudo cp nvim-linux-x86_64/bin/nvim /usr/bin/
sudo cp -r nvim-linux-x86_64/share/nvim/runtime /usr/share/nvim/
echo "alias vi='nvim'" >> ~/.bashrc

# version manager
curl https://mise.run | sh

# tmux plugin setup
git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm

source ~/.bashrc
