# Global configs
[tools]
neovim = "0.11.0"
ripgrep = "14.1.1"
tmux = "3.5a"
#uv = "0.7.9"
poetry = "1.6.1"
kubectl = "1.32.2"
argo = "3.5.6"
aws-cli = "2.7.30"
stern = "1.32.0"
kubie = "latest"
"npm:aws-azure-login" = "latest"
azure = "latest"
lazygit = "latest"
fd = "latest"
python = "3.11.12"
node = "24.0.0"
cosign = "latest"
sops = "3.10.2"
"aqua:jorgerojas26/lazysql" = "latest"

[settings]
idiomatic_version_file_enable_tools = ["python"]
